sudo: required

services:
  - docker

install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

env:
  - global:
    - FILE=docker-compose.travis.yml
    - LOCAL_IMAGE=uccourses_web
    - REGISTRY_IMAGE=almapp/uc-courses

before_script:
  - docker-compose --file=$FILE build

script:
  - docker-compose --file=$FILE run web npm test
  - docker-compose --file=$FILE stop
  - docker-compose --file=$FILE rm -f
